### ISSUE TITLE
Python script is not compressing

### ISSUE THREAD

**Issue by mdmcclel** [pepopo978/SuperWowCombatLogger#13]
The included python script is missing the flag which tells it what compression to use, so it defaults to zipfile.ZIP_STORED (no compression).  Simply add the extra parameter zipfile.ZIP_DEFLATED, as per:

![image](https://github.com/user-attachments/assets/9fdb5a44-da45-466f-901f-8b319bcec42f)

**Comment by pepopo978** [comment]
ty had noticed this too but forgot to change
