### ISSUE TITLE
Unknown player in Monkeylogs after formatting

### ISSUE THREAD

**Issue by Bombg** [pepopo978/SuperWowCombatLogger#9]
So I've had two different interesting things happen on my last log. One of our new members shown as unknown even after running the format for upload python script. I checked out his COMBATANT_INFO part of the log. He recently changed guilds to us(Onyfans), but it still shows him in his old guild. Also none of the items in the combatant info seem to be custom, so i'm not sure why he's showing as unknown.

The player that is showing unknown, still shows him in his old guild ERROR. 
`5/31 19:55:45.368  COMBATANT_INFO: 31.05.24 19:55:45&Ripmrbing&ROGUE&Scourge&2&nil&ERROR&Social&5&nil&12929:0:0:0&nil&nil&nil&16827:0:0:0&16909:1843:0:0&14641:1843:0:0&16825:0:0:0&16826:1843:0:0&17713:0:0:0&18500:0:0:0&13965:0:0:0&nil&10258:0:609:0&18832:1900:0:0&nil&18323:0:0:0&nil&nil`

Original log file
https://gist.githubusercontent.com/Bombg/07618adff9422a5b9df8c3407d49338b/raw/5187a3800f32494c85b4d4fa7c73e5061084252a/gistfile1.txt

The Monkeylog
http://monkeylogs.com/viewer/12600/base

**Comment by Bombg** [comment]
Uploaded a second log with the same person and now he's showing up on the new and old log as himself. 

The combatant info in the new log
`6/2 18:37:14.239  COMBATANT_INFO: 02.06.24 18:37:14&Ripmrbing&ROGUE&Scourge&2&nil&OnyFans&Tier 1 Sub&4&60436:1503:0:0&18404:0:0:0&16832:0:0:0&nil&50427:1892:0:0&16827:0:0:0&16909:1843:0:0&20186:1068:0:0&16825:1886:0:0&16826:1843:0:0&18500:0:0:0&13098:0:0:0&13965:0:0:0&80674:0:0:0&22712:0:0:0&114203:1900:0:0&114202:1900:0:0&18323:0:0:0&nil&nil`

**Comment by pepopo978** [comment]
Yea not too sure what happened might have just needed to wait a bit for it to process his armory I think that happens as a scheduled task but not entirely sure.

Like you said the main cause of that in the past was `any itemid > 25818 or enchantid > 3000  won't exist` and those combatant infos don't seen to have any
